#!/usr/bin/env python3
"""Derive configs/goal/*.yaml from configs/grpo/*-teacher.yaml.

Generated rather than written, so the training shape cannot drift from the arm it
is meant to be comparable with by a typo. Every key is copied; only the four this
arm actually changes are touched.
"""
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "configs" / "grpo"
DST = ROOT / "configs" / "goal"

HEADER = """\
# The goal-directed teacher arm. GENERATED by tools/make_goal_configs.py from
# {src} -- do not hand-edit; regenerate.
#
# Every training setting is that file's, unchanged: G=32, 16 problems, 512
# rollouts per step, 20 steps, the same sampling and the same grader. Four things
# differ, and they are the experiment:
#
#   reference_tests   removed. The open-ended arm showed the teacher three
#                     benchmark curves after every update. This arm shows the
#                     three target problems and nothing else.
#   targets_file      the three problems, statements only. Written into the
#                     system prompt at run start.
#   targets_sealed    their answers, encrypted. The orchestrator holds the key
#                     in memory and strips it from the teacher's environment.
#   target_eval       how the targets are graded after each update.
#
# The teacher for this arm is claude-opus-4-8, which is also the model whose
# public per-problem record chose the targets: it solves Q1 and Q2 and does not
# solve Q3.
"""

MAP = {"llama32-3b-teacher.yaml": "llama32-3b-goal.yaml",
       "qwen3-4b-nothink-teacher.yaml": "qwen3-4b-nothink-goal.yaml",
       "qwen3-4b-think-teacher.yaml": "qwen3-4b-think-goal.yaml"}


def main():
    DST.mkdir(parents=True, exist_ok=True)
    for src_name, dst_name in MAP.items():
        src = SRC / src_name
        if not src.is_file():
            sys.exit(f"missing {src}")
        cfg = yaml.safe_load(src.read_text())

        cfg.pop("reference_tests", None)
        cfg.pop("reference_data", None)
        cfg["output_path"] = "outputs/goal-teacher"
        cfg["targets_file"] = "data/goal_targets/arxiv3.problems.jsonl"
        cfg["targets_sealed"] = ".secrets/arxiv3.sealed"
        # samples=8 matches curriculum-rl's target evaluation. max_tokens and
        # max_model_len are inherited from teacher_eval, so thinking mode still
        # gets its 30k budget on the targets rather than the default 4k.
        cfg["target_eval"] = {"samples": 8, "verifier": "symbolic",
                              "headline_metric": "pass@1"}

        out = DST / dst_name
        out.write_text(HEADER.format(src=f"configs/grpo/{src_name}") + "\n" +
                       yaml.safe_dump(cfg, sort_keys=True, width=88,
                                      default_flow_style=False))
        print(f"  {out.relative_to(ROOT)}  <- configs/grpo/{src_name}")

        chk = yaml.safe_load(out.read_text())
        for k in ("group_size", "train_batch_size", "ppo_mini_batch_size",
                  "n_gpus", "steps", "keep_checkpoint_every", "base_model",
                  "grpo_config", "eval_base", "teacher_eval"):
            assert chk[k] == cfg[k], f"{dst_name}: {k} did not round-trip"
        assert "reference_tests" not in chk


if __name__ == "__main__":
    main()
